services:
  db:
    container_name: pharmacy_db_staging
    volumes:
      - postgres_data_staging:/var/lib/postgresql

  redis:
    container_name: pharmacy_redis_staging

  backend:
    container_name: pharmacy_backend_staging

  frontend:
    container_name: pharmacy_frontend_staging

  cloudflared:
    container_name: pharmacy_cloudflared_staging

volumes:
  postgres_data_staging:

networks:
  default:
    name: pharmacy_network_staging
